name: Build

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:

jobs:
    lint:
        if: github.event_name == 'pull_request'

        permissions:
            contents: read

        uses: ./.github/workflows/lint.yml
        with:
            diff-base: origin/${{ github.base_ref }}

    build-macos-matrix:
        permissions:
            contents: read

        strategy:
            fail-fast: false
            matrix:
                include:
                    - suffix: macOS ARM64 - SwiftUI - Release
                    - suffix: macOS ARM64 - SwiftUI - Debug
                    - suffix: macOS ARM64 - SDL - Release

        runs-on: macos-latest

        steps:
            - name: Set Xcode version
              uses: maxim-lobanov/setup-xcode@v1
              with:
                  xcode-version: latest-stable

            - name: Checkout Hydra
              uses: actions/checkout@v6
              with:
                  repository: SamoZ256/hydra
                  submodules: recursive
                  path: hydra
                  persist-credentials: true
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install dependencies
              run: |
                  brew install llvm dylibbundler boost fmt sdl3

            - name: Verify CMake version
              run: cmake --version

            - name: Set build flags
              run: |
                  if [[ "${{ matrix.suffix }}" == *"Release"* ]]; then
                    echo "BUILD_MODE=Release" >> $GITHUB_ENV
                  else
                    echo "BUILD_MODE=Debug" >> $GITHUB_ENV
                  fi
                  if [[ "${{ matrix.suffix }}" == *"SwiftUI"* ]]; then
                    echo "FRONTEND_MODE=SwiftUI" >> $GITHUB_ENV
                  else
                    echo "FRONTEND_MODE=SDL3" >> $GITHUB_ENV
                  fi

            - name: Build Hydra
              run: |
                  cmake hydra -B build \
                    -DCMAKE_OSX_ARCHITECTURES=arm64 \
                    -DCMAKE_BUILD_TYPE=${{ env.BUILD_MODE }} \
                    -DCLANG_TIDY_ENABLED=OFF \
                    -DMACOS_BUNDLE=ON \
                    -DFRONTEND=${{ env.FRONTEND_MODE }} \
                    -GNinja
                  ninja -C build
                  dylibbundler -of -cd -b -x build/bin/Hydra.app/Contents/MacOS/Hydra -d build/bin/Hydra.app/Contents/libs
                  while install_name_tool -delete_rpath @executable_path/../libs/ build/bin/Hydra.app/Contents/MacOS/Hydra 2>/dev/null; do :; done
                  install_name_tool -add_rpath @executable_path/../libs/ build/bin/Hydra.app/Contents/MacOS/Hydra
                  codesign --force --deep --preserve-metadata=entitlements,requirements,flags,runtime --sign - build/bin/Hydra.app/Contents/MacOS/Hydra

            - name: Create archive
              run: |
                  mkdir image
                  ln -s /Applications image/Applications
                  if [[ "${{ matrix.suffix }}" == *"SwiftUI"* ]]; then
                    mv build/bin/Hydra.app image/Hydra.app
                  else
                    mv build/bin/Hydra.app image/HydraSDL.app
                  fi
                  hdiutil create -volname "Hydra" -srcfolder image "Hydra - ${{ matrix.suffix }}.dmg"

            - name: Upload artifacts - ${{ matrix.suffix }}
              uses: actions/upload-artifact@v4
              with:
                  name: Hydra - ${{ matrix.suffix }}
                  path: Hydra - ${{ matrix.suffix }}.dmg
                  if-no-files-found: error

    build-macos:
        needs: build-macos-matrix
        if: ${{ !cancelled() }}

        permissions: {}

        runs-on: ubuntu-latest

        steps:
            - name: Check build results
              run: |
                  if [[ "${{ needs.build-macos-matrix.result }}" != "success" ]]; then
                    echo "build-macos-matrix: ${{ needs.build-macos-matrix.result }}"
                    exit 1
                  fi
